In [1]:
import pandas as pd

In [2]:
pd.read_csv("coffee.csv")

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [3]:
df=pd.read_csv("coffee.csv")

In [14]:
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [5]:
# df.sample(7)  # Gives random rows, and the values change every time you run it

df.sample(7, random_state=1)  # Gives random rows, but the values remain the same every time you run it

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15

In [6]:
df.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [7]:
df.columns

Index(['Day', 'Coffee Type', 'Units Sold'], dtype='object')

In [8]:
df.index

RangeIndex(start=0, stop=14, step=1)

In [9]:
df.index.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [10]:
df.info

<bound method DataFrame.info of           Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35>

In [19]:
df.describe()
# df["Day"].describe()
# df["Coffee Type"].describe()

       Units Sold
count   14.000000
mean    32.857143
std      9.346798
min     15.000000
25%     26.250000
50%     35.000000
75%     38.750000
max     45.000000

In [12]:
df.shape

(14, 3)

In [13]:
df.size

42

In [14]:
df.nunique()

Day            7
Coffee Type    2
Units Sold     7
dtype: int64

In [15]:
df["Coffee Type"].nunique()

2

# Accessing Data
* loc and iloc
* loc can acsc multiple value and single

In [18]:
# df.loc[Rows,columns]
# df.loc[5:9]
df.loc[[0,1,3,12]]

        Day Coffee Type  Units Sold
0    Monday    Espresso          25
1    Monday       Latte          15
3   Tuesday       Latte          20
12   Sunday    Espresso          45

In [20]:
# df.loc[[0,1,3,12],["Day"]]
# df.iloc[[0,1,3,12],[0,2]]         #it takes index
df.iloc[0:13,[0,2]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45

# Changes Index from 0,1,2

In [21]:
df.index=df["Day"]      #indexes are changed to days

In [23]:
df.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [28]:
df.loc[["Monday"],["Day","Units Sold"]]

           Day  Units Sold
Day
Monday  Monday          25
Monday  Monday          15

In [34]:
# df.loc[["Monday","Tuesday"]]
df.loc["Monday":"Wednesday"]

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25

In [40]:
df.iloc[[0, 1,2,3], [0, 1]]

             Day Coffee Type
Day
Monday    Monday    Espresso
Monday    Monday       Latte
Tuesday  Tuesday    Espresso
Tuesday  Tuesday       Latte

In [42]:
df.reset_index(drop=True, inplace=True)

In [43]:
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [54]:
df.loc[1:3,"Units Sold"]= 500

In [55]:
df.head(6)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte         500
2    Tuesday    Espresso         500
3    Tuesday       Latte         500
4  Wednesday    Espresso         100
5  Wednesday       Latte          25

In [57]:
df.loc[[0,2,3],"Coffee Type"]="Cappuccino"

In [58]:
df.head(7)

         Day Coffee Type  Units Sold
0     Monday  Cappuccino          25
1     Monday       Latte         500
2    Tuesday  Cappuccino         500
3    Tuesday  Cappuccino         500
4  Wednesday    Espresso         100
5  Wednesday       Latte          25
6   Thursday    Espresso          40

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     object
 1   Coffee Type  14 non-null     object
 2   Units Sold   14 non-null     int64
dtypes: int64(1), object(2)
memory usage: 468.0+ bytes

In [60]:
df.nunique()

Day            7
Coffee Type    3
Units Sold     7
dtype: int64

* iat and at to access specific data
* at can acs only single value not multiple

In [68]:
df.at[0,"Coffee Type"]

'Cappuccino'

In [69]:
df.head()

         Day Coffee Type  Units Sold
0     Monday  Cappuccino          25
1     Monday       Latte         500
2    Tuesday  Cappuccino         500
3    Tuesday  Cappuccino         500
4  Wednesday    Espresso         100

In [70]:
df.at[0,"Coffee Type"]="Espresso"

In [71]:
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte         500
2    Tuesday  Cappuccino         500
3    Tuesday  Cappuccino         500
4  Wednesday    Espresso         100

In [72]:
df.iat[0,1]                     #single element

'Espresso'

In [78]:
# df.Day           single word is acsd like this
# df["Day"]
df["Units Sold"]

0      25
1     500
2     500
3     500
4     100
5      25
6      40
7      30
8      45
9      35
10     45
11     35
12     45
13     35
Name: Units Sold, dtype: int64

In [80]:
df.sort_values("Units Sold",ascending=False)

          Day Coffee Type  Units Sold
1      Monday       Latte         500
2     Tuesday  Cappuccino         500
3     Tuesday  Cappuccino         500
4   Wednesday    Espresso         100
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25

In [88]:
# df.sort_values(["Units Sold","Day"],ascending=False)
# df.sort_values(["Units Sold","Day"],ascending=[0,1])
df.sort_values(["Units Sold","Coffee Type"],ascending=[0,0])

          Day Coffee Type  Units Sold
1      Monday       Latte         500
2     Tuesday  Cappuccino         500
3     Tuesday  Cappuccino         500
4   Wednesday    Espresso         100
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
5   Wednesday       Latte          25
0      Monday    Espresso          25

In [4]:
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35